name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12",]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install
      run: python -m pip install --upgrade pip && pip install .[dev] -c constraints
    - name: Lint
      run: ruff check --output-format=github ./src ./tests
    - name: Test
      run: pytest --rootdir= ./tests --doctest-modules --junitxml=junit/test-results.xml

    