name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12",]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.12"
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: uv sync --all-groups --all-extras --frozen
    - name: Lint
      run: uv run ruff check --output-format=github ./src ./tests
    - name: Test
      run: uv run pytest --rootdir= ./tests --doctest-modules --junitxml=junit/test-results.xml
