name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: uv sync --all-groups --all-extras --frozen --no-python-downloads

      - name: Lint
        run: uv run ruff check --output-format=github ./src ./tests && uv run pyright --project ./

      - name: Test
        run: uv run pytest --rootdir= ./tests --doctest-modules --junitxml=junit/test-results.xml

      - name: Build
        run: uv build
