name: publish

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12

      - name: Install
        run: uv sync --all-groups --all-extras --frozen --no-python-downloads

      - name: Lint
        run: uv run ruff check --output-format=github ./src ./tests

      - name: Test
        run: uv run pytest --rootdir= ./tests --doctest-modules --junitxml=junit/test-results.xml

      - name: Publish
        run: uv publish
